// หมวดสารบรรณตำรวจสำหรับแบบฝึกหัดและตัวกรอง
// แยกจากคลังความรู้ เพื่อให้เพิ่มข้อสอบตามหมวดได้โดยไม่เปลี่ยนเนื้อหาคลังความรู้

export const policeCorrespondenceTopics = [
  { id: 'pcorr-copy-extract', name: 'การคัดสำเนา', description: 'หลักการและขั้นตอนการคัดสำเนาเอกสารในราชการตำรวจ' },
  { id: 'pcorr-copy-certification', name: 'การคัดสำเนาและการรับรองสำเนา', description: 'การจัดทำสำเนาและการรับรองให้ถูกต้องตามระเบียบ' },
  { id: 'pcorr-certified-copy', name: 'การรับรองสำเนา', description: 'ผู้มีอำนาจ ข้อความ และวิธีรับรองสำเนา' },
  { id: 'pcorr-receive-send', name: 'การรับและส่งหนังสือ', description: 'ขั้นตอนรับ ส่ง และติดตามหนังสือราชการ' },
  { id: 'pcorr-inspection-signature', name: 'การลงชื่อตรวจ', description: 'การลงชื่อและตรวจสอบเอกสารตามสายงาน' },
  { id: 'pcorr-order', name: 'การสั่งการ', description: 'รูปแบบและลำดับการสั่งการในหน่วยงานตำรวจ' },
  { id: 'pcorr-police-abbreviations', name: 'คำย่อในราชการตำรวจ', description: 'คำย่อและชื่อหน่วยงานที่ใช้ในหนังสือราชการตำรวจ' },
  { id: 'pcorr-workday', name: 'งานปัด', description: 'คำและการดำเนินงานที่ใช้ในงานสารบรรณตำรวจ' },
  { id: 'pcorr-police-office-work', name: 'งานสารบรรณ ตร.', description: 'ระเบียบและแนวปฏิบัติงานสารบรรณของสำนักงานตำรวจแห่งชาติ' },
  { id: 'pcorr-electronic-correspondence', name: 'งานสารบรรณอิเล็กทรอนิกส์', description: 'การรับ ส่ง และจัดเก็บเอกสารด้วยระบบอิเล็กทรอนิกส์' },
  { id: 'pcorr-case-data', name: 'ข้อมูลคดีต่างๆ', description: 'การจัดการและการอ้างอิงข้อมูลคดีในงานเอกสาร' },
  { id: 'pcorr-receipt-stamp', name: 'ตรารับหนังสือ', description: 'การใช้ตรารับและการลงข้อมูลเมื่อรับหนังสือ' },
  { id: 'pcorr-traffic-announcement', name: 'ประกาศจราจร', description: 'การจัดทำและใช้ประกาศที่เกี่ยวกับงานจราจร' },
  { id: 'pcorr-certified-duplicate', name: 'รับรองสำเนา', description: 'การรับรองความถูกต้องของสำเนาเอกสาร' },
  { id: 'pcorr-command-method', name: 'วิธีสั่งการ', description: 'แนวปฏิบัติและถ้อยคำสำหรับการสั่งการ' },
  { id: 'pcorr-police-english', name: 'ศัพท์ภาษาอังกฤษ ตร.', description: 'คำศัพท์ภาษาอังกฤษที่พบในงานตำรวจและงานเอกสาร' },
  { id: 'pcorr-police-correspondence', name: 'สารบรรณตำรวจ', description: 'ภาพรวมวงจรเอกสารและระเบียบสารบรรณในสายงานตำรวจ' },
  { id: 'pcorr-police-secretariat', name: 'สำนักงานเลขานุการตำรวจแห่งชาติ', description: 'บทบาทและข้อมูลพื้นฐานของหน่วยงานเลขานุการตำรวจแห่งชาติ' },
  { id: 'pcorr-document-copy', name: 'สำเนาเอกสาร', description: 'การจัดทำ เก็บ และใช้อ้างอิงสำเนาเอกสาร' },
  { id: 'pcorr-stamped-book', name: 'หนังสือประทับตรา', description: 'ลักษณะและการใช้หนังสือประทับตรา' },
  { id: 'pcorr-outside-book', name: 'หนังสือภายนอก', description: 'รูปแบบและการใช้หนังสือภายนอกในการติดต่อราชการ' },
  { id: 'pcorr-inside-book', name: 'หนังสือภายใน', description: 'การติดต่อภายในด้วยบันทึกข้อความและหนังสือภายใน' },
  { id: 'pcorr-certificate', name: 'หนังสือรับรอง', description: 'ลักษณะและการจัดทำหนังสือรับรอง' },
  { id: 'pcorr-secret-book', name: 'หนังสือลับ', description: 'การจัดการหนังสือที่มีชั้นความลับ' },
  { id: 'pcorr-police-name-book', name: 'หนังสือในนาม ตร.', description: 'หนังสือที่จัดทำในนามสำนักงานตำรวจแห่งชาติ' },
  { id: 'pcorr-national-police-name-book', name: 'หนังสือในนามสำนักงานตำรวจแห่งชาติ', description: 'รูปแบบ ผู้ลงนาม และการใช้อำนาจในหนังสือของสำนักงานตำรวจแห่งชาติ' },
  { id: 'pcorr-document-unit', name: 'หน่วยงานสารบรรณ', description: 'หน้าที่และความรับผิดชอบของหน่วยงานสารบรรณ' },
  { id: 'pcorr-police-officer', name: 'เจ้าพนักงานตำรวจ', description: 'หน้าที่และการปฏิบัติงานของเจ้าพนักงานตำรวจที่เกี่ยวกับเอกสาร' },
  { id: 'pcorr-unit-code', name: 'เลขประจำหน่วยงาน', description: 'การใช้และอ้างอิงเลขประจำหน่วยงาน' },
  { id: 'pcorr-field-mail', name: 'ไปรษณีย์สนาม', description: 'การสื่อสารและรับส่งเอกสารผ่านไปรษณีย์สนาม' },
];
