// หมายเหตุ: คำถามในไฟล์นี้เป็น "ตัวอย่าง" สำหรับสาธิตการทำงานของระบบเท่านั้น
// ยังไม่ใช่ชุดข้อสอบจริงที่ผ่านการตรวจทาน ควรแทนที่ด้วยคลังข้อสอบจริงก่อนใช้งานจริง

export const questions = [
  // เทคโนโลยีสารสนเทศ (คอมพิวเตอร์)
  {
    id: 'it-1',
    subjectId: 'it',
    topicId: 'it-memory',
    question: 'หน่วยความจำประเภทใดที่ข้อมูลจะหายไปทันทีเมื่อปิดเครื่อง?',
    choices: ['ROM', 'RAM', 'Hard Disk', 'SSD'],
    answerIndex: 1,
    explanation: 'RAM (Random Access Memory) เป็นหน่วยความจำชั่วคราว ใช้เก็บข้อมูลระหว่างเปิดเครื่องเท่านั้น เมื่อปิดเครื่องข้อมูลจะหายไป',
  },
  {
    id: 'it-2',
    subjectId: 'it',
    topicId: 'it-network',
    question: 'HTTPS แตกต่างจาก HTTP อย่างไร?',
    choices: [
      'HTTPS เร็วกว่าเสมอ',
      'HTTPS มีการเข้ารหัสข้อมูลระหว่างส่ง',
      'HTTPS ใช้ได้เฉพาะมือถือ',
      'ไม่มีความแตกต่างกัน',
    ],
    answerIndex: 1,
    explanation: 'HTTPS คือ HTTP ที่เพิ่มการเข้ารหัสข้อมูล (SSL/TLS) ทำให้ข้อมูลที่ส่งระหว่างเครื่องผู้ใช้กับเว็บไซต์ปลอดภัยขึ้น',
  },
  {
    id: 'it-3',
    subjectId: 'it',
    topicId: 'it-office',
    question: 'ไฟล์เอกสาร Microsoft Word เวอร์ชันใหม่ใช้นามสกุลใด?',
    choices: ['.doc', '.docx', '.pdf', '.txt'],
    answerIndex: 1,
    explanation: 'ตั้งแต่ Microsoft Word 2007 เป็นต้นมา ใช้นามสกุลไฟล์ .docx ซึ่งเป็นรูปแบบ Open XML',
  },
  {
    id: 'it-4',
    subjectId: 'it',
    topicId: 'it-cyber',
    question:
      'การโจมตีทางไซเบอร์ประเภทใดที่ผู้โจมตีปลอมแปลงอีเมลหรือเว็บไซต์เพื่อหลอกให้เหยื่อเปิดเผยข้อมูลส่วนตัว เช่น รหัสผ่านหรือเลขบัตร?',
    choices: ['Phishing', 'Ransomware', 'DDoS', 'Malware'],
    answerIndex: 0,
    explanation: 'Phishing คือการหลอกลวงผ่านอีเมลหรือเว็บไซต์ปลอมเพื่อขโมยข้อมูลส่วนตัวของเหยื่อ',
  },
  {
    id: 'it-5',
    subjectId: 'it',
    topicId: 'it-cyber',
    question: 'มาตรการใดช่วยป้องกันบัญชีผู้ใช้จากการถูกเจาะรหัสผ่านได้ดีที่สุด?',
    choices: [
      'ตั้งรหัสผ่านเดียวกันทุกบัญชี',
      'เปิดใช้การยืนยันตัวตนสองขั้นตอน (2FA)',
      'ปิดโปรแกรมป้องกันไวรัส',
      'แชร์รหัสผ่านกับเพื่อนร่วมงาน',
    ],
    answerIndex: 1,
    explanation: 'การยืนยันตัวตนสองขั้นตอน (2FA) เพิ่มชั้นความปลอดภัย แม้รหัสผ่านจะรั่วไหลก็ยังต้องยืนยันอีกขั้นก่อนเข้าบัญชีได้',
  },
  {
    id: 'it-6',
    subjectId: 'it',
    topicId: 'it-os',
    question: 'ข้อใดคือระบบปฏิบัติการ (Operating System)?',
    choices: ['Windows', 'Microsoft Word', 'Google Chrome', 'Adobe Photoshop'],
    answerIndex: 0,
    explanation: 'Windows เป็นระบบปฏิบัติการที่ควบคุมการทำงานของฮาร์ดแวร์และรันโปรแกรมต่างๆ ส่วนตัวเลือกอื่นเป็นเพียงโปรแกรมประยุกต์',
  },
  {
    id: 'it-7',
    subjectId: 'it',
    topicId: 'it-os',
    question: 'ไฟล์นามสกุลใดใช้สำหรับไฟล์โปรแกรมที่เรียกใช้งานได้ (executable) บนระบบปฏิบัติการ Windows?',
    choices: ['.exe', '.txt', '.jpg', '.mp3'],
    answerIndex: 0,
    explanation: '.exe เป็นนามสกุลไฟล์โปรแกรมที่สามารถเรียกใช้งาน (execute) ได้บน Windows',
  },

  // งานสารบรรณ
  {
    id: 'corr-1',
    subjectId: 'correspondence',
    topicId: 'corr-types',
    question: 'หนังสือราชการที่ใช้ติดต่อระหว่างส่วนราชการ หรือติดต่อบุคคลภายนอก เรียกว่าอะไร?',
    choices: ['หนังสือภายใน', 'หนังสือภายนอก', 'หนังสือสั่งการ', 'หนังสือประชาสัมพันธ์'],
    answerIndex: 1,
    explanation: 'หนังสือภายนอก คือหนังสือติดต่อราชการที่เป็นแบบพิธีการ ใช้ระหว่างส่วนราชการ หรือระหว่างส่วนราชการกับบุคคลภายนอก',
  },
  {
    id: 'corr-2',
    subjectId: 'correspondence',
    topicId: 'corr-types',
    question: 'บันทึกข้อความ จัดอยู่ในหนังสือราชการประเภทใด?',
    choices: ['หนังสือภายนอก', 'หนังสือภายใน', 'หนังสือประทับตรา', 'หนังสือที่เจ้าหน้าที่จัดทำขึ้นเป็นหลักฐาน'],
    answerIndex: 1,
    explanation: 'บันทึกข้อความใช้ติดต่อภายในกระทรวง กรม หรือจังหวัดเดียวกัน จัดอยู่ในประเภทหนังสือภายใน',
  },
  {
    id: 'corr-3',
    subjectId: 'correspondence',
    topicId: 'corr-archive',
    question: 'ขั้นตอนสุดท้ายของการปฏิบัติงานสารบรรณเมื่อเรื่องเสร็จสิ้นแล้วคือข้อใด?',
    choices: ['การร่างหนังสือ', 'การเสนอหนังสือ', 'การเก็บรักษา/ทำลายหนังสือ', 'การลงทะเบียนรับ'],
    answerIndex: 2,
    explanation: 'เมื่อเรื่องดำเนินการเสร็จสิ้นแล้ว หนังสือจะถูกจัดเก็บตามระยะเวลาที่กำหนด และทำลายเมื่อครบกำหนดตามระเบียบ',
  },
  {
    id: 'corr-4',
    subjectId: 'correspondence',
    topicId: 'corr-draft',
    question: 'การร่างหนังสือราชการควรยึดหลักสำคัญข้อใดมากที่สุด?',
    choices: [
      'ใช้ถ้อยคำสละสลวยและยาวที่สุด',
      'ถูกต้อง ชัดเจน รัดกุม และสุภาพ',
      'ใช้คำศัพท์ภาษาต่างประเทศให้มาก',
      'เขียนตามความรู้สึกของผู้ร่าง',
    ],
    answerIndex: 1,
    explanation:
      'หลักการร่างหนังสือราชการคือต้องถูกต้องตามระเบียบ ชัดเจนเข้าใจง่าย รัดกุมไม่กำกวม และใช้ถ้อยคำสุภาพเหมาะสมกับผู้รับ',
  },
  {
    id: 'corr-5',
    subjectId: 'correspondence',
    topicId: 'corr-draft',
    question: 'ผู้มีอำนาจลงนามในหนังสือภายนอกซึ่งทำในนามส่วนราชการคือผู้ใด?',
    choices: [
      'เจ้าหน้าที่ผู้ร่างหนังสือ',
      'หัวหน้าส่วนราชการหรือผู้ที่ได้รับมอบหมาย',
      'เจ้าหน้าที่ธุรการทุกคน',
      'ผู้รับหนังสือ',
    ],
    answerIndex: 1,
    explanation:
      'หนังสือภายนอกเป็นหนังสือที่ทำในนามส่วนราชการ จึงต้องลงนามโดยหัวหน้าส่วนราชการ หรือผู้ที่ได้รับมอบหมายให้ปฏิบัติราชการแทน',
  },
  {
    id: 'corr-6',
    subjectId: 'correspondence',
    topicId: 'corr-regulation',
    question: 'ระเบียบสำนักนายกรัฐมนตรีว่าด้วยงานสารบรรณฉบับหลักที่ใช้อ้างอิงคือ พ.ศ. ใด?',
    choices: ['พ.ศ. 2516', 'พ.ศ. 2526', 'พ.ศ. 2536', 'พ.ศ. 2546'],
    answerIndex: 1,
    explanation:
      'ระเบียบสำนักนายกรัฐมนตรีว่าด้วยงานสารบรรณ พ.ศ. 2526 เป็นระเบียบหลักที่ใช้อ้างอิง และมีการแก้ไขเพิ่มเติมในภายหลัง',
  },
  {
    id: 'corr-7',
    subjectId: 'correspondence',
    topicId: 'corr-regulation',
    question: 'ตามระเบียบงานสารบรรณ คำว่า "งานสารบรรณ" หมายถึงงานที่เกี่ยวกับเรื่องใด?',
    choices: [
      'งานบริหารงานบุคคลทั้งหมด',
      'งานที่เกี่ยวกับการบริหารงานเอกสาร',
      'งานการเงินและบัญชี',
      'งานพัสดุและครุภัณฑ์',
    ],
    answerIndex: 1,
    explanation:
      'งานสารบรรณ หมายถึง งานที่เกี่ยวกับการบริหารงานเอกสาร ตั้งแต่การจัดทำ รับ-ส่ง เก็บรักษา ยืม จนถึงการทำลาย',
  },

  // กฎหมายที่ประชาชนควรรู้
  {
    id: 'law-1',
    subjectId: 'law',
    topicId: 'law-civil',
    question: 'บุคคลบรรลุนิติภาวะเมื่ออายุครบกี่ปีบริบูรณ์ (กรณีทั่วไป)?',
    choices: ['15 ปี', '18 ปี', '20 ปี', '21 ปี'],
    answerIndex: 2,
    explanation: 'ตามประมวลกฎหมายแพ่งและพาณิชย์ บุคคลย่อมพ้นจากภาวะผู้เยาว์และบรรลุนิติภาวะเมื่อมีอายุ 20 ปีบริบูรณ์',
  },
  {
    id: 'law-2',
    subjectId: 'law',
    topicId: 'law-criminal',
    question: 'การกระทำที่กฎหมายบัญญัติว่าเป็นความผิดและกำหนดโทษไว้ เรียกว่าอะไร?',
    choices: ['ความผิดทางแพ่ง', 'ความผิดทางอาญา', 'ความผิดทางปกครอง', 'ความผิดทางวินัย'],
    answerIndex: 1,
    explanation: 'ความผิดทางอาญาคือการกระทำที่กฎหมายอาญาบัญญัติว่าเป็นความผิดและมีบทลงโทษกำกับไว้ชัดเจน',
  },
  {
    id: 'law-3',
    subjectId: 'law',
    topicId: 'law-rights',
    question: 'ผู้ถูกจับกุมมีสิทธิที่จะไม่ให้การใดๆ ที่เป็นปฏิปักษ์ต่อตนเอง เรียกว่าสิทธิใด?',
    choices: ['สิทธิในการประกันตัว', 'สิทธิในการมีทนาย', 'สิทธิที่จะไม่ให้การปรักปรำตนเอง', 'สิทธิในการอุทธรณ์'],
    answerIndex: 2,
    explanation: 'ผู้ต้องหาหรือจำเลยมีสิทธิที่จะไม่ให้การใดๆ อันเป็นปฏิปักษ์ต่อตนเอง ซึ่งเป็นสิทธิพื้นฐานในกระบวนการยุติธรรมทางอาญา',
  },
  {
    id: 'law-4',
    subjectId: 'law',
    topicId: 'law-constitution',
    question: 'รัฐธรรมนูญมีสถานะอย่างไรเมื่อเทียบกับกฎหมายอื่นในระบบกฎหมายไทย?',
    choices: [
      'มีศักดิ์เท่ากับพระราชบัญญัติ',
      'เป็นกฎหมายสูงสุดของประเทศ',
      'มีศักดิ์ต่ำกว่าพระราชกฤษฎีกา',
      'ใช้บังคับเฉพาะหน่วยงานราชการ',
    ],
    answerIndex: 1,
    explanation:
      'รัฐธรรมนูญเป็นกฎหมายสูงสุดของประเทศ บทบัญญัติของกฎหมายใดที่ขัดหรือแย้งต่อรัฐธรรมนูญย่อมใช้บังคับมิได้',
  },
  {
    id: 'law-5',
    subjectId: 'law',
    topicId: 'law-constitution',
    question: 'อำนาจอธิปไตยตามรัฐธรรมนูญแห่งราชอาณาจักรไทยแบ่งออกเป็นกี่ฝ่าย?',
    choices: ['2 ฝ่าย', '3 ฝ่าย', '4 ฝ่าย', '5 ฝ่าย'],
    answerIndex: 1,
    explanation:
      'อำนาจอธิปไตยแบ่งเป็น 3 ฝ่าย ได้แก่ อำนาจนิติบัญญัติ อำนาจบริหาร และอำนาจตุลาการ',
  },
  {
    id: 'law-6',
    subjectId: 'law',
    topicId: 'law-police-act',
    question: 'หน่วยงานใดเป็นหน่วยงานหลักที่รับผิดชอบงานตำรวจของประเทศไทย?',
    choices: [
      'กรมการปกครอง',
      'สำนักงานตำรวจแห่งชาติ',
      'กระทรวงยุติธรรม',
      'สำนักงานอัยการสูงสุด',
    ],
    answerIndex: 1,
    explanation:
      'สำนักงานตำรวจแห่งชาติ (ตร.) เป็นหน่วยงานหลักที่รับผิดชอบงานตำรวจ ขึ้นตรงต่อนายกรัฐมนตรี',
  },
  {
    id: 'law-7',
    subjectId: 'law',
    topicId: 'law-police-act',
    question: 'ข้อใดคือภารกิจหลักตามอำนาจหน้าที่ของข้าราชการตำรวจ?',
    choices: [
      'พิจารณาพิพากษาคดี',
      'รักษาความสงบเรียบร้อยและป้องกันปราบปรามอาชญากรรม',
      'ตราพระราชบัญญัติ',
      'จัดเก็บภาษีอากร',
    ],
    answerIndex: 1,
    explanation:
      'ภารกิจหลักของตำรวจคือรักษาความสงบเรียบร้อย ความปลอดภัยของประชาชน และป้องกันปราบปรามอาชญากรรม ส่วนการพิพากษาคดีเป็นอำนาจของศาล',
  },

  // ความสามารถทั่วไป (คณิตศาสตร์)
  {
    id: 'apt-1',
    subjectId: 'aptitude',
    topicId: 'apt-ratio',
    question: 'ถ้า a : b = 2 : 3 และ b : c = 4 : 5 แล้ว a : c เท่ากับเท่าใด?',
    choices: ['8 : 15', '2 : 5', '6 : 8', '8 : 9'],
    answerIndex: 0,
    explanation: 'ทำให้ b เท่ากันก่อน: a:b = 8:12 และ b:c = 12:15 (คูณให้ b เท่ากับ 12) ดังนั้น a:c = 8:15',
  },
  {
    id: 'apt-2',
    subjectId: 'aptitude',
    topicId: 'apt-percent',
    question: '15% ของ 240 มีค่าเท่ากับเท่าใด?',
    choices: ['24', '30', '36', '40'],
    answerIndex: 2,
    explanation: '15% ของ 240 คำนวณจาก 240 x 15 / 100 = 36',
  },
  {
    id: 'apt-3',
    subjectId: 'aptitude',
    topicId: 'apt-series',
    question: 'อนุกรมต่อไปนี้ 2, 5, 10, 17, 26, ? ตัวเลขถัดไปคือข้อใด?',
    choices: ['33', '35', '37', '39'],
    answerIndex: 2,
    explanation: 'ผลต่างระหว่างพจน์เพิ่มขึ้นทีละ 2 (3, 5, 7, 9, ...) ดังนั้นพจน์ถัดไปคือ 26 + 11 = 37',
  },
  {
    id: 'apt-4',
    subjectId: 'aptitude',
    topicId: 'apt-set',
    question:
      'นักเรียน 40 คน ชอบวิชาคณิตศาสตร์ 25 คน ชอบวิชาภาษาไทย 18 คน และชอบทั้งสองวิชา 10 คน มีนักเรียนกี่คนที่ไม่ชอบทั้งสองวิชา?',
    choices: ['5 คน', '7 คน', '9 คน', '12 คน'],
    answerIndex: 1,
    explanation:
      'ผู้ที่ชอบอย่างน้อยหนึ่งวิชา = 25 + 18 − 10 = 33 คน ดังนั้นผู้ที่ไม่ชอบทั้งสองวิชา = 40 − 33 = 7 คน',
  },
  {
    id: 'apt-5',
    subjectId: 'aptitude',
    topicId: 'apt-set',
    question:
      'กำหนดให้ "นกทุกตัวบินได้" และ "เพนกวินเป็นนก" ข้อสรุปใดถูกต้องตามหลักตรรกศาสตร์จากข้อความข้างต้น?',
    choices: [
      'เพนกวินบินได้',
      'เพนกวินบินไม่ได้',
      'นกบางตัวไม่ใช่เพนกวิน',
      'สรุปไม่ได้',
    ],
    answerIndex: 0,
    explanation:
      'การให้เหตุผลแบบนิรนัยพิจารณาเฉพาะความสมเหตุสมผลจากข้อกำหนดที่ให้มา เมื่อนกทุกตัวบินได้ และเพนกวินเป็นนก จึงสรุปได้ว่าเพนกวินบินได้ (แม้จะไม่ตรงกับข้อเท็จจริงในโลกจริงก็ตาม)',
  },
  {
    id: 'apt-6',
    subjectId: 'aptitude',
    topicId: 'apt-prob',
    question: 'ทอดลูกเต๋า 1 ลูก 1 ครั้ง ความน่าจะเป็นที่จะได้แต้มเป็นเลขคู่เท่ากับเท่าใด?',
    choices: ['1/6', '1/3', '1/2', '2/3'],
    answerIndex: 2,
    explanation: 'แต้มเลขคู่มี 3 แบบ คือ 2, 4, 6 จากทั้งหมด 6 แบบ ดังนั้นความน่าจะเป็น = 3/6 = 1/2',
  },
  {
    id: 'apt-7',
    subjectId: 'aptitude',
    topicId: 'apt-prob',
    question: 'มีเสื้อ 4 ตัว และกางเกง 3 ตัว จะจัดชุดเสื้อกับกางเกงได้ทั้งหมดกี่ชุดที่แตกต่างกัน?',
    choices: ['7 ชุด', '10 ชุด', '12 ชุด', '15 ชุด'],
    answerIndex: 2,
    explanation: 'ใช้หลักการคูณ: เลือกเสื้อได้ 4 วิธี และเลือกกางเกงได้ 3 วิธี รวม 4 × 3 = 12 ชุด',
  },

  // ภาษาไทย
  {
    id: 'thai-1',
    subjectId: 'thai',
    topicId: 'thai-royal',
    question: 'คำราชาศัพท์ของคำว่า "กิน" เมื่อใช้กับพระภิกษุสงฆ์คือข้อใด?',
    choices: ['เสวย', 'ฉัน', 'รับประทาน', 'บริโภค'],
    answerIndex: 1,
    explanation: 'คำว่า "ฉัน" เป็นคำราชาศัพท์/คำสุภาพที่ใช้กับพระภิกษุสงฆ์ในความหมายว่า กิน',
  },
  {
    id: 'thai-2',
    subjectId: 'thai',
    topicId: 'thai-rhetoric',
    question: '"อุปมาอุปไมย" ในทางภาษาไทยหมายถึงข้อใด?',
    choices: ['การเปรียบเทียบ', 'การซ้ำคำ', 'การเล่นคำ', 'การขยายความ'],
    answerIndex: 0,
    explanation: 'อุปมาอุปไมย หมายถึง การเปรียบเทียบสิ่งหนึ่งกับอีกสิ่งหนึ่งเพื่อให้เห็นภาพชัดเจนขึ้น',
  },
  {
    id: 'thai-3',
    subjectId: 'thai',
    topicId: 'thai-spelling',
    question: 'คำในข้อใดเขียนถูกต้องตามหลักภาษาไทย?',
    choices: ['พฤษภาคม', 'พฤษภาคน', 'พฤษาคม', 'พรึกษาคม'],
    answerIndex: 0,
    explanation: '"พฤษภาคม" เป็นการเขียนที่ถูกต้อง หมายถึงเดือนที่ 5 ของปี',
  },
  {
    id: 'thai-4',
    subjectId: 'thai',
    topicId: 'thai-reading',
    question:
      'อ่านข้อความต่อไปนี้: "การออกกำลังกายอย่างสม่ำเสมอไม่เพียงช่วยให้ร่างกายแข็งแรง แต่ยังช่วยลดความเครียดและทำให้นอนหลับได้ดีขึ้น" ใจความสำคัญของข้อความนี้คือข้อใด?',
    choices: [
      'วิธีการออกกำลังกายที่ถูกต้อง',
      'ประโยชน์ของการออกกำลังกายอย่างสม่ำเสมอ',
      'สาเหตุของความเครียด',
      'ปัญหาการนอนไม่หลับ',
    ],
    answerIndex: 1,
    explanation:
      'ข้อความกล่าวถึงผลดีหลายด้านของการออกกำลังกาย ทั้งร่างกายแข็งแรง ลดความเครียด และนอนหลับดีขึ้น ใจความสำคัญจึงเป็นเรื่องประโยชน์ของการออกกำลังกาย',
  },
  {
    id: 'thai-5',
    subjectId: 'thai',
    topicId: 'thai-reading',
    question: 'การอ่านเพื่อจับใจความสำคัญ ผู้อ่านควรให้ความสนใจกับสิ่งใดมากที่สุด?',
    choices: [
      'จำนวนคำในแต่ละย่อหน้า',
      'ประโยคใจความสำคัญของแต่ละย่อหน้า',
      'ชื่อผู้เขียนบทความ',
      'ความสวยงามของตัวอักษร',
    ],
    answerIndex: 1,
    explanation:
      'การจับใจความสำคัญต้องหาประโยคใจความสำคัญ (ประโยคหลัก) ของแต่ละย่อหน้า แล้วนำมาสรุปรวมเป็นใจความสำคัญของเรื่อง',
  },
  {
    id: 'thai-6',
    subjectId: 'thai',
    topicId: 'thai-compound',
    question: 'คำในข้อใดเป็น "คำสมาส"?',
    choices: ['ราชการ', 'ไปมา', 'กินข้าว', 'เดินเล่น'],
    answerIndex: 0,
    explanation:
      '"ราชการ" มาจาก ราช + การ เป็นคำบาลี-สันสกฤตนำมาประกอบกันโดยไม่มีการกลมกลืนเสียง จึงเป็นคำสมาส',
  },
  {
    id: 'thai-7',
    subjectId: 'thai',
    topicId: 'thai-compound',
    question: 'ข้อใดคือลักษณะสำคัญที่ทำให้ "คำสนธิ" ต่างจาก "คำสมาส"?',
    choices: [
      'คำสนธิมีการกลมกลืนเสียงตรงรอยต่อของคำ',
      'คำสนธิต้องเป็นคำไทยแท้เท่านั้น',
      'คำสนธิมีความยาวมากกว่าเสมอ',
      'คำสนธิใช้เฉพาะในบทกวี',
    ],
    answerIndex: 0,
    explanation:
      'คำสมาสคือการนำคำบาลี-สันสกฤตมาต่อกันตรงๆ ส่วนคำสนธิมีการเชื่อมและกลมกลืนเสียงตรงรอยต่อ เช่น วิทย + อาลัย = วิทยาลัย',
  },

  // ภาษาต่างประเทศ (ภาษาอังกฤษ)
  {
    id: 'eng-1',
    subjectId: 'english',
    topicId: 'eng-grammar',
    question: 'Choose the correct word: "She ___ to work every day."',
    choices: ['go', 'goes', 'going', 'gone'],
    answerIndex: 1,
    explanation: 'ประธาน "She" เป็นเอกพจน์บุรุษที่ 3 กริยาในรูป present simple ต้องเติม s/es จึงใช้ "goes"',
  },
  {
    id: 'eng-2',
    subjectId: 'english',
    topicId: 'eng-vocab',
    question: 'What is a synonym of the word "assist"?',
    choices: ['ignore', 'help', 'attack', 'delay'],
    answerIndex: 1,
    explanation: '"Assist" แปลว่า ช่วยเหลือ ซึ่งมีความหมายใกล้เคียงกับคำว่า "help"',
  },
  {
    id: 'eng-3',
    subjectId: 'english',
    topicId: 'eng-police',
    question: '"Police officer" แปลเป็นภาษาไทยตรงกับข้อใด?',
    choices: ['ทนายความ', 'เจ้าหน้าที่ตำรวจ', 'พยาบาล', 'ครู'],
    answerIndex: 1,
    explanation: '"Police officer" หมายถึง เจ้าหน้าที่ตำรวจ',
  },
  {
    id: 'eng-4',
    subjectId: 'english',
    topicId: 'eng-reading',
    question:
      'Read: "Traffic accidents often increase during the rainy season because wet roads make it harder for vehicles to stop quickly." According to the passage, why do accidents increase?',
    choices: [
      'Because there are more cars on the road',
      'Because wet roads make stopping harder',
      'Because drivers do not wear seatbelts',
      'Because the roads are being repaired',
    ],
    answerIndex: 1,
    explanation:
      'ข้อความระบุเหตุผลไว้ชัดเจนว่า "wet roads make it harder for vehicles to stop quickly" คือถนนเปียกทำให้รถหยุดได้ยากขึ้น',
  },
  {
    id: 'eng-5',
    subjectId: 'english',
    topicId: 'eng-reading',
    question:
      'Read: "The police station is open 24 hours a day. However, the document service counter is only available from 8 a.m. to 4 p.m." When can you use the document service counter?',
    choices: ['At any time, 24 hours', 'Only at 8 a.m.', 'Between 8 a.m. and 4 p.m.', 'Only after 4 p.m.'],
    answerIndex: 2,
    explanation:
      'คำว่า "However" แสดงการขัดแย้ง แม้สถานีตำรวจเปิด 24 ชั่วโมง แต่เคาน์เตอร์บริการเอกสารเปิดเฉพาะ 8 โมงเช้าถึง 4 โมงเย็น',
  },
  {
    id: 'eng-6',
    subjectId: 'english',
    topicId: 'eng-dialogue',
    question: 'A: "Excuse me, could you tell me the way to the police station?" B: "___"',
    choices: [
      'Sure, go straight and turn left at the corner.',
      'Yes, I am a police officer.',
      'No, thank you very much.',
      'It is raining today.',
    ],
    answerIndex: 0,
    explanation:
      'คำถามเป็นการขอทราบเส้นทาง คำตอบที่เหมาะสมจึงต้องเป็นการบอกทาง คือ "Sure, go straight and turn left at the corner."',
  },
  {
    id: 'eng-7',
    subjectId: 'english',
    topicId: 'eng-dialogue',
    question: 'A: "I\'m sorry for being late." B: "___"',
    choices: [
      'That\'s all right. Please have a seat.',
      'You\'re welcome to leave now.',
      'Congratulations on your success.',
      'How much does it cost?',
    ],
    answerIndex: 0,
    explanation:
      'เมื่อมีผู้กล่าวขอโทษ การตอบรับที่เหมาะสมคือการให้อภัย เช่น "That\'s all right." ซึ่งแปลว่า ไม่เป็นไร',
  },
];
