// หมายเหตุ: คำถามในไฟล์นี้เป็น "ตัวอย่าง" สำหรับสาธิตการทำงานของระบบเท่านั้น
// ยังไม่ใช่ชุดข้อสอบจริงที่ผ่านการตรวจทาน ควรแทนที่ด้วยคลังข้อสอบจริงก่อนใช้งานจริง

export const questions = [
  // เทคโนโลยีสารสนเทศ (คอมพิวเตอร์)
  {
    id: 'it-1',
    subjectId: 'it',
    topicId: 'it-memory',
    question: 'หน่วยความจำประเภทใดที่ข้อมูลจะหายไปทันทีเมื่อปิดเครื่อง?',
    choices: ['ROM', 'RAM', 'Hard Disk', 'SSD'],
    answerIndex: 1,
    explanation: 'RAM (Random Access Memory) เป็นหน่วยความจำชั่วคราว ใช้เก็บข้อมูลระหว่างเปิดเครื่องเท่านั้น เมื่อปิดเครื่องข้อมูลจะหายไป',
  },
  {
    id: 'it-2',
    subjectId: 'it',
    topicId: 'it-network',
    question: 'HTTPS แตกต่างจาก HTTP อย่างไร?',
    choices: [
      'HTTPS เร็วกว่าเสมอ',
      'HTTPS มีการเข้ารหัสข้อมูลระหว่างส่ง',
      'HTTPS ใช้ได้เฉพาะมือถือ',
      'ไม่มีความแตกต่างกัน',
    ],
    answerIndex: 1,
    explanation: 'HTTPS คือ HTTP ที่เพิ่มการเข้ารหัสข้อมูล (SSL/TLS) ทำให้ข้อมูลที่ส่งระหว่างเครื่องผู้ใช้กับเว็บไซต์ปลอดภัยขึ้น',
  },
  {
    id: 'it-3',
    subjectId: 'it',
    topicId: 'it-office',
    question: 'ไฟล์เอกสาร Microsoft Word เวอร์ชันใหม่ใช้นามสกุลใด?',
    choices: ['.doc', '.docx', '.pdf', '.txt'],
    answerIndex: 1,
    explanation: 'ตั้งแต่ Microsoft Word 2007 เป็นต้นมา ใช้นามสกุลไฟล์ .docx ซึ่งเป็นรูปแบบ Open XML',
  },
  {
    id: 'it-4',
    subjectId: 'it',
    topicId: 'it-cyber',
    question:
      'การโจมตีทางไซเบอร์ประเภทใดที่ผู้โจมตีปลอมแปลงอีเมลหรือเว็บไซต์เพื่อหลอกให้เหยื่อเปิดเผยข้อมูลส่วนตัว เช่น รหัสผ่านหรือเลขบัตร?',
    choices: ['Phishing', 'Ransomware', 'DDoS', 'Malware'],
    answerIndex: 0,
    explanation: 'Phishing คือการหลอกลวงผ่านอีเมลหรือเว็บไซต์ปลอมเพื่อขโมยข้อมูลส่วนตัวของเหยื่อ',
  },
  {
    id: 'it-5',
    subjectId: 'it',
    topicId: 'it-cyber',
    question: 'มาตรการใดช่วยป้องกันบัญชีผู้ใช้จากการถูกเจาะรหัสผ่านได้ดีที่สุด?',
    choices: [
      'ตั้งรหัสผ่านเดียวกันทุกบัญชี',
      'เปิดใช้การยืนยันตัวตนสองขั้นตอน (2FA)',
      'ปิดโปรแกรมป้องกันไวรัส',
      'แชร์รหัสผ่านกับเพื่อนร่วมงาน',
    ],
    answerIndex: 1,
    explanation: 'การยืนยันตัวตนสองขั้นตอน (2FA) เพิ่มชั้นความปลอดภัย แม้รหัสผ่านจะรั่วไหลก็ยังต้องยืนยันอีกขั้นก่อนเข้าบัญชีได้',
  },
  {
    id: 'it-6',
    subjectId: 'it',
    topicId: 'it-os',
    question: 'ข้อใดคือระบบปฏิบัติการ (Operating System)?',
    choices: ['Windows', 'Microsoft Word', 'Google Chrome', 'Adobe Photoshop'],
    answerIndex: 0,
    explanation: 'Windows เป็นระบบปฏิบัติการที่ควบคุมการทำงานของฮาร์ดแวร์และรันโปรแกรมต่างๆ ส่วนตัวเลือกอื่นเป็นเพียงโปรแกรมประยุกต์',
  },
  {
    id: 'it-7',
    subjectId: 'it',
    topicId: 'it-os',
    question: 'ไฟล์นามสกุลใดใช้สำหรับไฟล์โปรแกรมที่เรียกใช้งานได้ (executable) บนระบบปฏิบัติการ Windows?',
    choices: ['.exe', '.txt', '.jpg', '.mp3'],
    answerIndex: 0,
    explanation: '.exe เป็นนามสกุลไฟล์โปรแกรมที่สามารถเรียกใช้งาน (execute) ได้บน Windows',
  },

  // งานสารบรรณ
  {
    id: 'corr-1',
    subjectId: 'correspondence',
    topicId: 'corr-types',
    question: 'หนังสือราชการที่ใช้ติดต่อระหว่างส่วนราชการ หรือติดต่อบุคคลภายนอก เรียกว่าอะไร?',
    choices: ['หนังสือภายใน', 'หนังสือภายนอก', 'หนังสือสั่งการ', 'หนังสือประชาสัมพันธ์'],
    answerIndex: 1,
    explanation: 'หนังสือภายนอก คือหนังสือติดต่อราชการที่เป็นแบบพิธีการ ใช้ระหว่างส่วนราชการ หรือระหว่างส่วนราชการกับบุคคลภายนอก',
  },
  {
    id: 'corr-2',
    subjectId: 'correspondence',
    topicId: 'corr-types',
    question: 'บันทึกข้อความ จัดอยู่ในหนังสือราชการประเภทใด?',
    choices: ['หนังสือภายนอก', 'หนังสือภายใน', 'หนังสือประทับตรา', 'หนังสือที่เจ้าหน้าที่จัดทำขึ้นเป็นหลักฐาน'],
    answerIndex: 1,
    explanation: 'บันทึกข้อความใช้ติดต่อภายในกระทรวง กรม หรือจังหวัดเดียวกัน จัดอยู่ในประเภทหนังสือภายใน',
  },
  {
    id: 'corr-3',
    subjectId: 'correspondence',
    topicId: 'corr-archive',
    question: 'ขั้นตอนสุดท้ายของการปฏิบัติงานสารบรรณเมื่อเรื่องเสร็จสิ้นแล้วคือข้อใด?',
    choices: ['การร่างหนังสือ', 'การเสนอหนังสือ', 'การเก็บรักษา/ทำลายหนังสือ', 'การลงทะเบียนรับ'],
    answerIndex: 2,
    explanation: 'เมื่อเรื่องดำเนินการเสร็จสิ้นแล้ว หนังสือจะถูกจัดเก็บตามระยะเวลาที่กำหนด และทำลายเมื่อครบกำหนดตามระเบียบ',
  },

  // กฎหมายที่ประชาชนควรรู้
  {
    id: 'law-1',
    subjectId: 'law',
    topicId: 'law-civil',
    question: 'บุคคลบรรลุนิติภาวะเมื่ออายุครบกี่ปีบริบูรณ์ (กรณีทั่วไป)?',
    choices: ['15 ปี', '18 ปี', '20 ปี', '21 ปี'],
    answerIndex: 2,
    explanation: 'ตามประมวลกฎหมายแพ่งและพาณิชย์ บุคคลย่อมพ้นจากภาวะผู้เยาว์และบรรลุนิติภาวะเมื่อมีอายุ 20 ปีบริบูรณ์',
  },
  {
    id: 'law-2',
    subjectId: 'law',
    topicId: 'law-criminal',
    question: 'การกระทำที่กฎหมายบัญญัติว่าเป็นความผิดและกำหนดโทษไว้ เรียกว่าอะไร?',
    choices: ['ความผิดทางแพ่ง', 'ความผิดทางอาญา', 'ความผิดทางปกครอง', 'ความผิดทางวินัย'],
    answerIndex: 1,
    explanation: 'ความผิดทางอาญาคือการกระทำที่กฎหมายอาญาบัญญัติว่าเป็นความผิดและมีบทลงโทษกำกับไว้ชัดเจน',
  },
  {
    id: 'law-3',
    subjectId: 'law',
    topicId: 'law-rights',
    question: 'ผู้ถูกจับกุมมีสิทธิที่จะไม่ให้การใดๆ ที่เป็นปฏิปักษ์ต่อตนเอง เรียกว่าสิทธิใด?',
    choices: ['สิทธิในการประกันตัว', 'สิทธิในการมีทนาย', 'สิทธิที่จะไม่ให้การปรักปรำตนเอง', 'สิทธิในการอุทธรณ์'],
    answerIndex: 2,
    explanation: 'ผู้ต้องหาหรือจำเลยมีสิทธิที่จะไม่ให้การใดๆ อันเป็นปฏิปักษ์ต่อตนเอง ซึ่งเป็นสิทธิพื้นฐานในกระบวนการยุติธรรมทางอาญา',
  },

  // ความสามารถทั่วไป (คณิตศาสตร์)
  {
    id: 'apt-1',
    subjectId: 'aptitude',
    topicId: 'apt-ratio',
    question: 'ถ้า a : b = 2 : 3 และ b : c = 4 : 5 แล้ว a : c เท่ากับเท่าใด?',
    choices: ['8 : 15', '2 : 5', '6 : 8', '8 : 9'],
    answerIndex: 0,
    explanation: 'ทำให้ b เท่ากันก่อน: a:b = 8:12 และ b:c = 12:15 (คูณให้ b เท่ากับ 12) ดังนั้น a:c = 8:15',
  },
  {
    id: 'apt-2',
    subjectId: 'aptitude',
    topicId: 'apt-percent',
    question: '15% ของ 240 มีค่าเท่ากับเท่าใด?',
    choices: ['24', '30', '36', '40'],
    answerIndex: 2,
    explanation: '15% ของ 240 คำนวณจาก 240 x 15 / 100 = 36',
  },
  {
    id: 'apt-3',
    subjectId: 'aptitude',
    topicId: 'apt-series',
    question: 'อนุกรมต่อไปนี้ 2, 5, 10, 17, 26, ? ตัวเลขถัดไปคือข้อใด?',
    choices: ['33', '35', '37', '39'],
    answerIndex: 2,
    explanation: 'ผลต่างระหว่างพจน์เพิ่มขึ้นทีละ 2 (3, 5, 7, 9, ...) ดังนั้นพจน์ถัดไปคือ 26 + 11 = 37',
  },

  // ภาษาไทย
  {
    id: 'thai-1',
    subjectId: 'thai',
    topicId: 'thai-royal',
    question: 'คำราชาศัพท์ของคำว่า "กิน" เมื่อใช้กับพระภิกษุสงฆ์คือข้อใด?',
    choices: ['เสวย', 'ฉัน', 'รับประทาน', 'บริโภค'],
    answerIndex: 1,
    explanation: 'คำว่า "ฉัน" เป็นคำราชาศัพท์/คำสุภาพที่ใช้กับพระภิกษุสงฆ์ในความหมายว่า กิน',
  },
  {
    id: 'thai-2',
    subjectId: 'thai',
    topicId: 'thai-rhetoric',
    question: '"อุปมาอุปไมย" ในทางภาษาไทยหมายถึงข้อใด?',
    choices: ['การเปรียบเทียบ', 'การซ้ำคำ', 'การเล่นคำ', 'การขยายความ'],
    answerIndex: 0,
    explanation: 'อุปมาอุปไมย หมายถึง การเปรียบเทียบสิ่งหนึ่งกับอีกสิ่งหนึ่งเพื่อให้เห็นภาพชัดเจนขึ้น',
  },
  {
    id: 'thai-3',
    subjectId: 'thai',
    topicId: 'thai-spelling',
    question: 'คำในข้อใดเขียนถูกต้องตามหลักภาษาไทย?',
    choices: ['พฤษภาคม', 'พฤษภาคน', 'พฤษาคม', 'พรึกษาคม'],
    answerIndex: 0,
    explanation: '"พฤษภาคม" เป็นการเขียนที่ถูกต้อง หมายถึงเดือนที่ 5 ของปี',
  },

  // ภาษาต่างประเทศ (ภาษาอังกฤษ)
  {
    id: 'eng-1',
    subjectId: 'english',
    topicId: 'eng-grammar',
    question: 'Choose the correct word: "She ___ to work every day."',
    choices: ['go', 'goes', 'going', 'gone'],
    answerIndex: 1,
    explanation: 'ประธาน "She" เป็นเอกพจน์บุรุษที่ 3 กริยาในรูป present simple ต้องเติม s/es จึงใช้ "goes"',
  },
  {
    id: 'eng-2',
    subjectId: 'english',
    topicId: 'eng-vocab',
    question: 'What is a synonym of the word "assist"?',
    choices: ['ignore', 'help', 'attack', 'delay'],
    answerIndex: 1,
    explanation: '"Assist" แปลว่า ช่วยเหลือ ซึ่งมีความหมายใกล้เคียงกับคำว่า "help"',
  },
  {
    id: 'eng-3',
    subjectId: 'english',
    topicId: 'eng-police',
    question: '"Police officer" แปลเป็นภาษาไทยตรงกับข้อใด?',
    choices: ['ทนายความ', 'เจ้าหน้าที่ตำรวจ', 'พยาบาล', 'ครู'],
    answerIndex: 1,
    explanation: '"Police officer" หมายถึง เจ้าหน้าที่ตำรวจ',
  },
];
